version: "3.8"
services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8080:8080"
  camera:
    build: 
      context: .
      dockerfile: Dockerfile.camera
    environment:
        SCHEME: "http"
        HOST: "api"
        PORT: "8080"
